language: node_js
node_js:
  - "node"
  - "8"
script:
  - push
  - cd packages/golang
  - npm install && npm run build
  - pop
  - push
  - cd packages/html-symbol-entities
  - npm install && npm run build
  - pop
  - push
  - cd packages/php
  - npm install && npm run build
  - pop
  - push
  - cd packages/python
  - npm install && npm run build
  - pop
  - push
  - cd packages/cpp
  - npm install && npm run build
  - pop

